// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AuthData struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Credentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type GroupData struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type HabitData struct {
	ID          string         `json:"id"`
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Schedule    *ScheduleInput `json:"schedule,omitempty"`
	GroupID     *string        `json:"groupId,omitempty"`
}

type NewSuccess struct {
	Date    string `json:"date"`
	HabitID string `json:"habitId"`
}

type Success struct {
	ID    string `json:"id"`
	Date  string `json:"date"`
	Habit *Habit `json:"habit"`
}
