name: Continuous integration pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Install dependencies
        run: go get -t ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Generate GITHUB_SHA
        id: github-sha
        shell: bash
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "::set-output name=sha::$SHORT_SHA"

      - name: Publish Image to Digital Ocean Container Registry
        shell: bash
        run: |
          doctl registry login --expiry-seconds 600
          docker build . -t registry.digitalocean.com/infamous55/habit_tracker:${{steps.github-sha.outputs.sha}}
          docker push registry.digitalocean.com/infamous55/habit_tracker:${{steps.github-sha.outputs.sha}}
